#!/bin/bash
# Remove any existing installations
rm -rf "/Library/Audio/Plug-Ins/VST3/The Kings Cab.vst3"
rm -rf "/Library/Audio/Plug-Ins/Components/The Kings Cab.component"
rm -rf "/Library/Application Support/Avid/Audio/Plug-Ins/The Kings Cab.aaxplugin"
exit 0
